name: InfactionsCore
version: '${version}'
main: me.ventilover.infactionscore.InfactionsCore
api-version: '1.20'
description: The main plugin for the faction system
authors:
  - LordSchocki
  - VentiLover
  - skuchsa44

commands:

  faction:
    description: Used as a prefix for other faction related commands
    usage: /faction [Command]
    permission: infactionscore.factioncommand

  fhelp:
    description: See other faction commands
    usage: /faction help
    permission: infactionscore.factionhelp
  flist:
    description: See other factions on the server
    usage: /faction list
    permission: infactionscore.factionlist


permissions:
  infactionscore.factionhelp:
    description: Allows use of the faction command
    default: true
  infactionscore.factionlist:
    description: Allows use of the faction list command
    default: true
  infactionscore.factioncommand:
    description: Permission to use the prefix command
    default: true

